apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd  # This is where Argo CD is installed
spec:
  project: default
  source:
    repoURL: https://github.com/Manoj-kumar423/GitOps.git
    targetRevision: HEAD
    path: manifests  # Change this if your manifests are inside a folder like "k8s" or "manifests"
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # You can change this to any namespace you want your app to run in
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
